services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: esercitazione-db
    volumes:
      - esercitazione-db:/var/lib/postgresql/data

volumes:
  esercitazione-db: